### ISSUE TITLE
Pool and wallet tabs are missing from EOS mode

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/bancor-ui#39]
Since refactoring, we've lost the ability to add and remove liquidity for EOS, and lost the wallet feature. 

Before:
<img width="324" alt="Screen Shot 2020-01-14 at 2 56 14 PM" src="https://user-images.githubusercontent.com/37008057/72377748-13243100-36de-11ea-9589-92c7b0317f9b.png">

After:
<img width="442" alt="Screen Shot 2020-01-14 at 2 57 07 PM" src="https://user-images.githubusercontent.com/37008057/72377796-29ca8800-36de-11ea-9f59-5ed295d7e0ce.png">

**Comment by Velua** [comment]
These nav links we're omitted due to the priority being placed on Add/Remove liquidity. 

Given that these single relays are eventually being decommissioned do we want to support adding/removing liquidity for them? I was thinking we'd add that feature for the multi-contract then allow some migration to come across. 

Nor do the single converters support the `fund` method so we'd have to use the previous version of buying the smart tokens with one reserve token then buying more with the other reserve token.

**Comment by Velua** [comment]
@DenisCarriere what do you think?

I vote we don't bother with adding/removing liquidity to relays that are going out of service unless we later add some migration feature.

But will do whatever you guys see fit.

**Comment by Velua** [comment]
![Screen Shot 2020-01-15 at 10 53 15 mornin](https://user-images.githubusercontent.com/8017434/72395458-45d53480-3785-11ea-811d-e2268b9715ea.png)

**Comment by Velua** [comment]
Will re-add wallet, @chillsauce is this required before we can deploy to production?

**Comment by chillsauce** [comment]
Let's get the wallet added back to the EOS view as part of the post-production updates we're doing for this milestone.
